"""empty message

Revision ID: 64269b5916ab
Revises: 2cd74c1328cf
Create Date: 2020-11-10 22:20:59.931991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64269b5916ab'
down_revision = '2cd74c1328cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_point_log', sa.Column('user_point_id', sa.BigInteger(), nullable=True))
    op.drop_column('user_point_log', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_point_log', sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column('user_point_log', 'user_point_id')
    # ### end Alembic commands ###
