"""takedown point and voucher

Revision ID: 82e627abad8d
Revises: e16ada22c05f
Create Date: 2020-11-14 03:37:49.112880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82e627abad8d'
down_revision = 'e16ada22c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_point_log')
    op.drop_table('user_point')
    op.drop_table('point')
    op.drop_table('voucher_log')
    op.drop_index('code', table_name='voucher')
    op.drop_table('voucher')
    op.add_column('user', sa.Column('jumlah_transaksi', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('total_transaksi', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_transaksi')
    op.drop_column('user', 'jumlah_transaksi')
    op.create_table('voucher',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('discount_type', mysql.ENUM('PERCENT', 'AMOUNT', 'FREESHIPPING'), nullable=True),
    sa.Column('value_type', mysql.ENUM('RUPIAH', 'POINT'), nullable=True),
    sa.Column('discount_value', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('valid_from', sa.DATE(), nullable=True),
    sa.Column('valid_to', sa.DATE(), nullable=True),
    sa.Column('limit', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('code', 'voucher', ['code'], unique=True)
    op.create_table('voucher_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('voucher_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('point',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('level', mysql.ENUM('SILVER', 'GOLD', 'PLATINUM'), nullable=False),
    sa.Column('point', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_point',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('total_point', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_point_log',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_point_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('status_point', mysql.ENUM('CREDIT', 'DEBIT'), nullable=False),
    sa.Column('point', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('balance_point', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
