"""empty message

Revision ID: de77f511fd1a
Revises: 64269b5916ab
Create Date: 2020-11-11 00:22:17.379863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de77f511fd1a'
down_revision = '64269b5916ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Enum('SILVER', 'GOLD', 'PLATINUM'), nullable=False),
    sa.Column('point', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    # ### end Alembic commands ###
