"""added message model

Revision ID: e16ada22c05f
Revises: f80891523870
Create Date: 2020-11-12 11:54:06.252962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16ada22c05f'
down_revision = 'f80891523870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_thread_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_message_thread_id'), 'message', ['message_thread_id'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('message_thread',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('from_user_id', sa.BigInteger(), nullable=True),
    sa.Column('to_user_id', sa.BigInteger(), nullable=True),
    sa.Column('message_type', sa.Enum('STOK', 'PRODUK', 'COMPLAINT'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_thread_from_user_id'), 'message_thread', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_message_thread_to_user_id'), 'message_thread', ['to_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_thread_to_user_id'), table_name='message_thread')
    op.drop_index(op.f('ix_message_thread_from_user_id'), table_name='message_thread')
    op.drop_table('message_thread')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_message_thread_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
